const MOVIES = [
 {id:'sheroes',title:'Sheroes',local:true,status:'soon',release:'02 OCT 2026',language:'Urdu',genre:'Action / Anthology',runtime:'1h 40m',director:'Saqib Khan & Badar Mehmood',cast:'Ushna Shah • Kinza Hashmi • Zara Noor Abbas',desc:'Three worlds. Three gripping stories. One anthology film bringing standalone stories together.',poster:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=85',cities:['Karachi','Lahore','Islamabad'],trailer:'https://www.youtube.com/results?search_query=Sheroes+Pakistani+movie+trailer',source:'https://geofilms.tv/movies/sheroes/'},
 {id:'lutt',title:'Lutt Mubarak',local:false,status:'now',release:'NOW',language:'Punjabi',genre:'Comedy / Drama',runtime:'2h 10m',director:'Amrit Raaj Chadhaa',cast:'Harish Verma • Kanika Mann • Rupinder Rupi',desc:'A young man fights to reclaim his family’s dignity after his mother is falsely accused.',poster:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=85',cities:['Lahore','Sialkot'],trailer:'https://www.youtube.com/results?search_query=Lutt+Mubarak+trailer',source:'https://cinestar.pk/Browsing/Movies/Details/h-HO00001231'},
 {id:'avengers',title:'Avengers: Endgame Encore',local:false,status:'now',release:'NOW',language:'English',genre:'Action',runtime:'3h 01m',director:'Anthony & Joe Russo',cast:'Robert Downey Jr. • Chris Evans • Scarlett Johansson',desc:'The Avengers assemble once more in an encore theatrical presentation.',poster:'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&w=900&q=85',cities:['Karachi','Lahore','Islamabad','Rawalpindi','Sialkot'],trailer:'https://www.youtube.com/results?search_query=Avengers+Endgame+trailer',source:'https://www.showtimes.pk/'},
 {id:'heart',title:'Heart of the Beast',local:false,status:'now',release:'NOW',language:'English',genre:'Action',runtime:'1h 41m',director:'—',cast:'—',desc:'Currently listed in Pakistani cinema schedules.',poster:'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=900&q=85',cities:['Karachi','Lahore','Sialkot'],trailer:'https://www.youtube.com/results?search_query=Heart+of+the+Beast+movie+trailer',source:'https://www.showtimes.pk/'},
 {id:'resident',title:'Resident Evil',local:false,status:'now',release:'NOW',language:'English',genre:'Horror / Action',runtime:'1h 35m',director:'—',cast:'—',desc:'A horror-action title currently appearing in Pakistani cinema listings.',poster:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85',cities:['Karachi','Lahore'],trailer:'https://www.youtube.com/results?search_query=Resident+Evil+2026+trailer',source:'https://www.showtimes.pk/'},
 {id:'forgotten',title:'Forgotten Island',local:false,status:'now',release:'NOW',language:'English',genre:'Action',runtime:'1h 49m',director:'—',cast:'—',desc:'An action title currently listed on Pakistani screens.',poster:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85',cities:['Karachi','Lahore'],trailer:'https://www.youtube.com/results?search_query=Forgotten+Island+movie+trailer',source:'https://www.showtimes.pk/'},
 {id:'delhi',title:'Delhi Gate',local:true,status:'soon',release:'30 OCT 2026',language:'Urdu',genre:'Drama',runtime:'TBA',director:'TBA',cast:'TBA',desc:'Listed for an upcoming Pakistan cinema release.',poster:'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=900&q=85',cities:['Lahore','Karachi','Islamabad'],trailer:'https://www.youtube.com/results?search_query=Delhi+Gate+Pakistani+film+trailer',source:'https://derooj.com/'},
 {id:'btown',title:'B Town',local:false,status:'soon',release:'16 OCT 2026',language:'English',genre:'TBA',runtime:'TBA',director:'TBA',cast:'TBA',desc:'Coming soon to selected Pakistani cinemas.',poster:'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=900&q=85',cities:['Lahore'],trailer:'https://www.youtube.com/results?search_query=B+Town+2026+movie+trailer',source:'https://derooj.com/'}
];
